# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests and Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
         - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    strategy:
      matrix:
        node-version: [20.x]
    env:
      TEST_DB: mongodb://localhost:27017/bookify

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Wait for MongoDB to be ready
      run: |
       for i in {1..30}; do
        nc -z localhost 27017 && echo "MongoDB is up" && exit 0
        echo "Waiting for MongoDB..."
        sleep 1
       done
       echo "MongoDB did not start in time" && exit 1

    - name: Run tests
      env: 
        TEST_DB : ${{ env.TEST_DB }}

      run: npm test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name : Login to docker hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with: 
        push: true
        tags: ryankaleligabriel/bookify-api-${{ github.sha }}:latest

    

